In [49]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [50]:
cars_data=pd.read_csv('C:\car prediction\Cardetails.csv')

In [51]:
cars_data.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014.0,450000.0,145500.0,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014.0,370000.0,120000.0,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006.0,158000.0,140000.0,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010.0,225000.0,127000.0,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007.0,130000.0,120000.0,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0

In [52]:
cars_data.drop(columns=['torque'],inplace=True)

In [53]:
cars_data.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,Maruti Swift Dzire VDI,2014.0,450000.0,145500.0,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014.0,370000.0,120000.0,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,5.0
2,Honda City 2017-2020 EXi,2006.0,158000.0,140000.0,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,5.0
3,Hyundai i20 Sportz Diesel,2010.0,225000.0,127000.0,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,5.0
4,Maruti Swift VXI BSIII,2007.0,130000.0,120000.0,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,5.0

In [54]:
cars_data.shape

(8128, 12)

In [55]:
##preprocessing

In [56]:
cars_data.dropna(inplace=True)

In [57]:
cars_data.shape

(7906, 12)

In [58]:
cars_data.duplicated().sum()

np.int64(1189)

In [59]:
cars_data = cars_data.drop_duplicates().reset_index(drop=True)

In [60]:
cars_data.shape

(6717, 12)

In [61]:

cars_data

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,Maruti Swift Dzire VDI,2014.0,450000.0,145500.0,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014.0,370000.0,120000.0,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,5.0
2,Honda City 2017-2020 EXi,2006.0,158000.0,140000.0,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,5.0
3,Hyundai i20 Sportz Diesel,2010.0,225000.0,127000.0,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,5.0
4,Maruti Swift VXI BSIII,2007.0,130000.0,120000.0,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6712,Maruti Wagon R VXI BS IV with ABS,2013.0,260000.0,50000.0,Petrol,Individual,Manual,Second Owner,18.9 kmpl,998 CC,67.1 bhp,5.0
6713,Hyundai i20 Magna 1.4 CRDi,2014.0,475000.0,80000.0,Diesel,Individual,Manual,Second Owner,22.54 kmpl,1396 CC,88.73 bhp,5.0
6714,Hyundai i20 Magna,2013.0,320000.0,110000.0,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,5.0
6715,Hyundai Verna CRDi SX,2007.0,135000.0,119000.0,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,5.0
6716,Maruti Swift Dzire ZDi,2009.0,382000.0,120000.0,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,5.0

In [62]:
cars_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6717 entries, 0 to 6716
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6717 non-null   str
 1   year           6717 non-null   float64
 2   selling_price  6717 non-null   float64
 3   km_driven      6717 non-null   float64
 4   fuel           6717 non-null   str
 5   seller_type    6717 non-null   str
 6   transmission   6717 non-null   str
 7   owner          6717 non-null   str
 8   mileage        6717 non-null   str
 9   engine         6717 non-null   str
 10  max_power      6717 non-null   str
 11  seats          6717 non-null   float64
dtypes: float64(4), str(8)
memory usage: 1.2 MB

In [63]:
for col in cars_data.columns:
    print('Unique values of ' + col)
    print(cars_data[col].unique())
    print("=====================\n")

Unique values of name
<ArrowStringArray>
[                      'Maruti Swift Dzire VDI',
                 'Skoda Rapid 1.5 TDI Ambition',
                     'Honda City 2017-2020 EXi',
                    'Hyundai i20 Sportz Diesel',
                       'Maruti Swift VXI BSIII',
                'Hyundai Xcent 1.2 VTVT E Plus',
                 'Maruti Wagon R LXI DUO BSIII',
                           'Maruti 800 DX BSII',
                             'Toyota Etios VXD',
         'Ford Figo Diesel Celebration Edition',
 ...
                    'Toyota Innova 2.5 E 7 STR',
                            'Honda City ZXi AT',
                 'Ford Fiesta 1.4 Duratorq EXI',
                           'Chevrolet Cruze LT',
                  'Maruti Celerio ZXI AMT BSIV',
                        'Tata Bolt Revotron XM',
           'Tata Manza Aura (ABS) Safire BS IV',
                   'Tata Nexon 1.5 Revotorq XT',
     'Ford Freestyle Titanium Plus Diesel BSIV',
 'Toyota Innova 2.5 GX (Diesel) 8 Seater BS IV']
Length: 1983, dtype: str
=====================

Unique values of year
[2014. 2006. 2010. 2007. 2017. 2001. 2011. 2013. 2005. 2009. 2016. 2012.
 2002. 2015. 2018. 2019. 2008. 2020. 1999. 2000. 2003. 2004. 1994. 1998.
 1997. 1995. 1996.]
=====================

Unique values of selling_price
[  450000.   370000.   158000.   225000.   130000.   440000.    96000.
    45000.   350000.   200000.   500000.    92000.   280000.   180000.
   400000.   778000.   150000.   680000.   174000.   950000.   525000.
   600000.   575000.   275000.   300000.   220000.   254999.   670000.
   730000.   650000.   330000.   366000.  1149000.   425000.  2100000.
   925000.   675000.   819999.   390000.  1500000.   700000.  1450000.
  1090000.   850000.  1650000.  1750000.  1590000.  1689999.  1425000.
   265000.   190000.   630000.   540000.   448000.   745000.  1025000.
   235000.  1700000.  1200000.   610000.  2500000.   484999.   315000.
   290000.   455000.   351000.   175000.   565000.   120000.   725000.
   185000.   615000.   270000.   625000.   866000.   375000.   522000.
   451999.   475000.   780000.   595000.  1140000.   360000.   105000.
   135000.   690000.  3975000.  5150000.  3200000.  4100000.  4500000.
  6000000.  3790000.  5800000.  1864999.  2700000.   795000.  3400000.
  2650000.   535000.  5850000.   975000.   805000.  2625000.   811000.
   550000.   645000.  2550000.   599000.   875000.   894999.   340000.
  1525000.  2150000.  1900000.  2900000. 10000000.   160000.   515000.
    40000.   480000.   487000.   386000.   100000.   490000.   345000.
    85000.   215000.   320000.   459999.    65000.   720000.   800000.
   520000.   580000.   420000.  1250000.   830000.   335000.   329000.
   775000.   524000.   245000.   910000.   900000.   250000.  1100000.
   640000.   409999.   165000.    80000.  1000000.   110000.   170000.
  1380000.  1300000.   530000.   310000.  1150000.   380000.   404000.
   114999.   465000.   210000.  4600000.   509999.    90000.   409000.
   395000.    81000.   555000.   229999.  1210000.   325000.    60000.
    89000.   434999.  3000000.   570000.  1550000.    64000.   140000.
   503000.  3800000.  2000000.   740000.   750000.  5400000.  5500000.
   779000.  2475000.   240000.  1085000.    95000.  1290000.   219000.
   260000.   840000.   292000.   385000.  1050000.   735000.   560000.
   585000.   760000.   430000.   643000.   285000.   660000.   268000.
    88000.   561000.   755000.   125000.  1600000.   801000.   317000.
   495000.   236000.  1800000.   415000.   217000.   466000.   605000.
  1350000.   337000.   655000.   196000.   299000.   634000.  1225000.
   238000.   590000.   195000.   715000.   168000.   531000.  1625000.
   145000.   441000.    67500.   321000.   298000.  1075000.   681000.
   810000.   573000.   101000.  1019999.   244000.  1165000.   241000.
   327000.   620000.   204999.   576000.   695000.   231000.   261000.
   371000.   421000.   710000.  1040000.   199000.   305000.  1745000.
   611000.    75000.    55000.  1325000.   885000.   108000.   272000.
  1125000.   388000.   757000.   626000.   793000.  3750000.  1400000.
  1925000.   844999.  2940000.  1825000.   890000.   770000.   467000.
   711000.   511000.   166000.   392000.   833000.    35000.   880000.
  1030000.   521000.   451000.   472000.   649000.   429000.  1576000.
   825000.   470000.  1560000.  1950000.   786000.   731000.   191000.
   651000.   445000.    93150.   403000.   144000.    52000.   302000.
   869999.   155000.   246000.   405000.    70000.  3250000.  1143000.
   635000.  1575000.   318000.   152000.   248000.  1465000.  1080000.
   678000.  1460000.   756000.   665000.  2950000.   377000.  1675000.
   169000.   685000.   749000.   899000.   259000.   416000.   773000.
   889000.   118000.   256000.  1888000.    99000.  2280000.    31504.
   295000.   444000.   860000.  2450000.   198000.  2825000.  2125000.
  3350000.   365000.   919999.  2600000.   839000.  1594000.   161000.
   423000.   551000.    50000.   411000.  1530000.   376000.  1850000.
    86000.   822000.    30000.   252000.   131000.   128000.   790000.
   604000.  1175000.   141000.   151000.   577000.    83000.   946000.
   356000.   955000.   978999.   348000.   399000.   362000.   499000.
   358000.   278000.   426000.   211000.  1270000.   426999.   960000.
  1031000.    72000.   479000.   764000.  2199000.  3600000.   184000.
   119000.   267000.   328000.   112999.    39000.  2850000.  2800000.
  3900000.   221000.   631000.   308000.   940000.   361000.   355000.
  7200000.   930000.  1670000.   980000.   486000.   242000.   654000.
   835000.   408000.    94500.  1110000.   438999.   911999.   693000.
   449000.  1390000.   698000.   539000.   765000.   562000.   571000.
   589000.   227999.  1151000.  1295000.  4090000.   347000.   493000.
   545000.  1475000.   287000.  1630000.   501000.   181000.  2711000.
  1035000.   316000.   813000.  1190000.   378000.   156000.   194000.
   754000.    55599.  1511000.    78000.   250999.   312000.    66000.
   369000.   149000.   752000.   142000.   111000.   206000.   567000.
   699000.   632000.   905000.  1145000.    58000.   179000.  1515000.
   178000.   222000.   387000.  1405000.   282000.   458000.   157000.
   497000.  1227000.   574000.   121000.  3100000.    68000.  1920000.
   808000.   512000.   671000.   799000.  1365000.  1490000.    80500.
   189000.   892000.    93000.  1680000.   667000.   204000.    42000.
   694000.   861999.   476999.  5200000.  2375000.  2750000.  1385000.
   785000.  1275000.  1748999.   132000.    33351.  2064000.   469000.
   906000.   797000.  6223000.  5923000.  6523000.   122000.   891000.
   346000.   532000.   974000.   483000.   138000.   432000.  1757000.
   412000.   126000.   736000.   579000.   187000.  4000000.  1898999.
   482000.   401000.   737000.   291000.   999000.   957000.   834000.
   297000.   669000.   616000.   129000.   115999.   861000.  3251000.
   911000.   148000.   433000.   488000.    67000.   516000.   136000.
    29999.   124000.  1938000.   172000.    59000.  3500000.   537000.
   849000.   851000.   597000.   741000.   556000.   549000.   679000.
   969999.  1237000.    31000.   666000.    54000.   374000.   455999.
   453000.   258000.   428000.   262000.   389000.   339000.   277000.
   578000.   684000.   949000.   227000.  5830000.   721000.   751000.
  2400000.   990000.  1282000.  1147000.   558000.   722000.   563000.
  2300000.  2200000.   488999.   276000.   434000.   372000.  1520000.
   202999.   541000.   254000.   528000.   102000.   311000.   977000.
  1251000.  1445000.    98000.    59259.   153000.  1051000.   591000.
   319000.   454000.  1160000.  3300000.   791000.   802999.  1789999.
  1044999.   279000.   944999.  1859000.  2175000.   430999.   803999.
   934000.   357000.   965000.   341000.    75527.  1132000.   352000.
   252999.   313000.   391000.  2051000.   212000.  2575000.  1516000.
   359000.   209000.  1220000.  1180000.    45957.  1265000.   382000.
   526000.    90177.    46000.   307000.   746000.]
=====================

Unique values of km_driven
[1.455000e+05 1.200000e+05 1.400000e+05 1.270000e+05 4.500000e+04
 1.750000e+05 5.000000e+03 9.000000e+04 1.690000e+05 6.800000e+04
 1.000000e+05 4.000000e+04 7.000000e+04 5.300000e+04 8.000000e+04
 5.000000e+04 7.200000e+04 3.500000e+04 2.800000e+04 2.500000e+04
 2.388000e+03 1.620000e+04 1.000000e+04 1.500000e+04 4.200000e+04
 6.000000e+04 7.600000e+04 2.890000e+04 8.630000e+04 2.330000e+04
 3.260000e+04 1.030000e+04 7.700000e+04 9.900000e+04 2.780000e+04
 4.980000e+04 1.510000e+05 5.470000e+04 6.400000e+04 6.300000e+04
 1.277000e+05 3.390000e+04 5.900000e+04 1.100000e+05 1.470000e+05
 3.000000e+04 1.350000e+05 9.850000e+03 7.800000e+04 1.700000e+05
 4.900000e+04 3.200000e+04 3.800000e+04 4.400000e+04 5.550000e+04
 6.150000e+04 1.500000e+05 3.780000e+04 1.140000e+05 4.800000e+04
 6.900000e+04 1.300000e+04 7.613900e+04 6.500000e+04 1.303000e+03
 3.180000e+04 2.000000e+04 1.700000e+04 2.100000e+04 3.700000e+04
 2.950000e+04 7.500000e+03 1.900000e+04 4.100000e+04 3.900000e+04
 2.200000e+04 4.700000e+04 7.220000e+04 4.990000e+04 9.000000e+03
 1.100000e+04 9.500000e+04 1.800000e+04 4.610000e+04 1.600000e+04
 9.654000e+03 2.430000e+04 4.216300e+04 8.000000e+03 1.200000e+04
 7.100000e+04 9.500000e+03 3.660000e+04 1.400000e+04 1.206000e+05
 8.600000e+04 7.800000e+03 3.137700e+04 7.500000e+04 9.300000e+04
 1.250000e+05 1.350000e+04 1.625000e+05 9.250000e+04 1.580000e+05
 2.000000e+03 1.810000e+05 1.930000e+05 1.223580e+05 9.520000e+04
 3.303300e+04 6.306300e+04 2.078900e+05 7.976000e+03 1.650000e+04
 9.936100e+04 3.300000e+04 8.010000e+04 1.600000e+05 2.600000e+04
 2.900000e+04 5.800000e+04 3.600000e+04 1.850000e+05 1.620000e+05
 6.700000e+04 5.200000e+04 6.808900e+04 5.834300e+04 3.881700e+04
 5.649400e+04 7.932800e+04 5.621000e+03 2.553800e+04 6.977900e+04
 5.629000e+04 8.500000e+03 7.032000e+03 1.060000e+05 2.400000e+05
 2.140000e+05 1.000000e+03 2.650000e+05 1.340000e+05 2.136000e+03
 2.500000e+05 1.300000e+05 9.950000e+04 1.190000e+05 4.466500e+04
 1.230000e+05 3.400000e+04 1.460000e+05 8.500000e+04 2.018500e+05
 4.600000e+04 1.900000e+05 4.300000e+04 1.420000e+04 1.910000e+04
 5.400000e+04 1.015000e+05 5.573500e+04 1.500000e+03 1.814910e+05
 5.331900e+04 4.090600e+04 3.171100e+04 4.375500e+04 6.669300e+04
 5.954900e+04 9.438500e+04 7.373000e+04 2.218890e+05 1.161040e+05
 1.505460e+05 1.481200e+05 1.420000e+05 1.260000e+05 2.400000e+04
 1.010000e+05 1.680000e+05 1.650000e+05 9.850000e+04 9.800000e+04
 7.780000e+04 5.149200e+04 1.360000e+05 9.100000e+04 1.670000e+05
 1.800000e+05 6.000000e+03 9.150000e+04 1.324780e+05 5.100000e+04
 1.050000e+05 1.375000e+05 8.800000e+04 1.560600e+05 1.070000e+05
 5.700000e+04 3.000000e+05 2.000000e+05 1.894500e+04 1.440000e+05
 1.078250e+05 1.620000e+03 1.410000e+05 1.080000e+05 5.500000e+04
 3.794400e+04 9.040000e+04 9.600000e+04 1.936230e+05 6.318600e+04
 2.190000e+05 2.300000e+04 9.400000e+04 1.405000e+05 1.430000e+05
 1.950000e+05 3.600030e+05 8.079000e+03 1.143680e+05 7.999000e+04
 8.163200e+04 1.552010e+05 1.015040e+05 9.016500e+04 8.601700e+04
 8.503600e+04 1.255310e+05 2.060000e+05 4.970000e+04 7.400000e+04
 6.550000e+03 5.600000e+04 4.177900e+04 3.100000e+04 1.353400e+04
 7.000000e+03 2.815600e+04 6.330900e+04 1.550000e+05 1.150000e+04
 3.000000e+03 1.570000e+05 2.700000e+04 2.630000e+04 8.910000e+04
 1.040000e+05 2.100000e+05 2.160000e+05 8.400000e+04 1.610000e+05
 7.211300e+04 1.130000e+05 9.644300e+04 5.150000e+04 1.045000e+05
 4.910200e+04 8.100000e+04 2.270000e+05 1.170000e+05 8.576000e+03
 1.972300e+04 2.144600e+04 5.228900e+04 5.223600e+04 5.447000e+04
 2.547100e+04 3.392800e+04 5.973600e+04 5.429000e+04 2.118000e+03
 6.137900e+04 5.854400e+04 7.438100e+04 6.398200e+04 5.642900e+04
 1.950000e+04 5.683200e+04 3.052800e+04 6.528500e+04 2.010200e+04
 5.238000e+04 7.425000e+04 5.724700e+04 1.780000e+05 4.232300e+04
 4.246200e+04 5.472300e+04 4.254500e+04 2.037500e+04 4.397800e+04
 4.020000e+04 2.723300e+04 2.883200e+04 1.030000e+05 1.425000e+05
 1.150000e+05 3.550000e+04 1.750000e+04 9.200000e+04 4.500000e+03
 8.300000e+04 6.750000e+03 1.850000e+04 5.047800e+04 9.200000e+03
 2.300000e+03 4.295000e+03 5.229000e+03 4.701000e+03 6.757000e+03
 2.818200e+04 1.153300e+04 1.168800e+04 5.772800e+04 2.371200e+04
 7.067000e+04 4.338100e+04 7.901100e+04 5.850000e+04 4.350000e+04
 1.270000e+04 4.945500e+04 4.681500e+04 3.340000e+05 1.008750e+05
 1.180000e+05 1.280000e+05 1.440300e+05 1.760000e+05 8.900000e+04
 9.700000e+04 1.280000e+04 6.510000e+04 1.520000e+04 8.200000e+04
 1.165000e+05 1.450000e+05 7.300000e+04 1.132260e+05 1.605000e+05
 1.320000e+05 2.170000e+05 1.390000e+05 3.500000e+03 6.200000e+04
 1.500000e+06 1.200050e+05 1.683000e+04 9.346800e+04 1.658900e+04
 5.320100e+04 2.527200e+04 5.361900e+04 6.001000e+03 2.020000e+05
 7.171700e+04 8.432100e+04 1.770000e+05 2.050000e+05 4.180000e+04
 8.870000e+04 1.880000e+05 2.250000e+05 5.500000e+03 4.875000e+03
 2.700000e+03 5.851100e+04 2.623500e+04 2.676600e+04 1.600000e+03
 2.452200e+04 1.366300e+04 5.894500e+04 3.750000e+05 1.569750e+05
 2.762000e+04 1.432000e+05 1.380000e+05 1.890000e+05 1.560000e+05
 1.080000e+04 6.750000e+04 2.550000e+05 7.185000e+04 1.120000e+05
 1.590000e+05 7.613100e+04 5.177700e+04 6.478800e+04 4.695100e+04
 7.453700e+04 2.350000e+04 6.860000e+04 1.388700e+04 6.600000e+04
 2.440000e+04 2.750000e+04 6.784000e+04 3.800000e+05 1.128800e+05
 6.191500e+04 1.840000e+05 6.200000e+03 1.670000e+04 7.967000e+03
 9.656000e+03 6.860900e+04 3.336000e+04 1.431700e+04 8.723700e+04
 6.296000e+04 2.663400e+04 1.637200e+05 6.799800e+04 2.070600e+04
 1.005810e+05 6.730300e+04 7.913900e+04 8.478400e+04 1.303760e+05
 3.350000e+04 2.205300e+04 7.843200e+04 2.700000e+05 7.200000e+03
 1.175000e+05 7.850000e+04 1.157170e+05 4.000000e+03 2.643200e+04
 4.670200e+04 4.670600e+04 5.352300e+04 5.636500e+04 4.956300e+04
 5.643200e+04 5.236500e+04 5.351200e+04 4.653300e+04 5.863200e+04
 6.530000e+04 3.939500e+04 2.300000e+05 3.250000e+04 6.480000e+04
 2.480000e+05 6.644400e+04 2.184630e+05 1.530000e+05 8.718500e+04
 1.370000e+05 3.564000e+03 4.875600e+04 8.032200e+04 1.730000e+05
 1.480000e+05 6.500000e+03 2.200000e+05 1.089570e+05 2.220000e+04
 2.600000e+05 4.210800e+04 7.900000e+04 1.710000e+04 4.300100e+04
 1.006000e+05 9.238500e+04 1.160000e+05 7.250000e+04 8.250000e+04
 5.060000e+04 1.210000e+05 1.019030e+05 8.556800e+04 3.100000e+03
 1.860000e+05 5.930000e+04 8.932200e+04 4.830000e+04 2.351100e+04
 2.251200e+04 6.290000e+04 5.244200e+04 3.415600e+04 3.415200e+04
 6.284100e+04 3.860000e+04 2.765400e+04 4.869800e+04 3.299500e+04
 9.015000e+04 8.570000e+04 2.533900e+04 4.123200e+04 6.824000e+04
 9.265100e+04 8.875400e+04 2.370000e+04 6.950000e+04 2.805000e+04
 2.294700e+04 7.672000e+03 3.665900e+04 4.450000e+04 9.900000e+03
 1.243160e+05 6.544000e+03 4.960000e+04 1.980000e+05 1.039940e+05
 3.500800e+04 3.110000e+04 4.231200e+04 5.489100e+04 1.889000e+04
 7.501000e+04 4.337000e+03 1.449500e+04 8.358500e+04 4.840600e+04
 5.623900e+04 3.324300e+04 1.585800e+04 8.784700e+04 8.700000e+04
 1.120720e+05 5.226900e+04 1.578000e+04 2.360457e+06 1.088000e+05
 1.250000e+04 5.774140e+05 1.219410e+05 1.521860e+05 8.224600e+04
 8.958000e+04 2.789000e+03 3.527800e+04 2.860000e+03 7.856200e+04
 3.608800e+04 1.290000e+05 5.000000e+05 1.330000e+05 6.450000e+04
 2.450000e+04 4.550000e+04 7.150000e+04 9.350000e+04 6.030000e+04
 4.439100e+04 5.631500e+04 1.515100e+04 1.143210e+05 3.733300e+04
 3.300000e+05 2.910000e+05 2.150000e+04 1.970000e+05 4.030000e+04
 3.003000e+04 2.902900e+04 7.207200e+04 8.208200e+04 8.060000e+04
 5.860900e+04 3.300300e+04 1.655000e+05 5.800000e+03 6.870000e+04
 1.029960e+05 9.650000e+04 5.241200e+04 8.547200e+04 8.745200e+04
 6.653000e+04 3.233100e+04 1.720000e+05 2.345600e+04 1.365000e+05
 1.110000e+05 4.250000e+04 4.720000e+04 2.460000e+05 5.200000e+03
 1.050000e+04 9.333100e+04 1.090000e+05 5.400000e+03 1.020000e+05
 2.970000e+04 7.600000e+03 2.934000e+04 8.080000e+04 2.426500e+04
 5.690000e+04 8.820000e+04 4.080000e+04 8.588000e+03 3.050000e+05
 2.120000e+05 1.012000e+05 1.791500e+05 8.448700e+04 2.640000e+05
 5.114600e+04 2.980000e+05 1.490000e+05 2.919770e+05 3.680000e+04
 5.220000e+04 2.482000e+05 7.720000e+03 5.788200e+04 2.420000e+05
 5.538000e+04 1.881600e+04 3.301900e+04 4.774700e+04 4.590000e+04
 6.869700e+04 1.472790e+05 2.470000e+04 4.352600e+04 5.588500e+04
 1.603400e+04 1.560400e+05 9.341500e+04 1.220000e+05 6.851900e+04
 2.296600e+04 2.350000e+03 5.987200e+04 9.118200e+04 5.950000e+04
 7.550000e+04 1.525000e+05 6.912300e+04 7.752400e+04 4.052300e+04
 2.360000e+04 2.900000e+05 2.417700e+04 1.217790e+05 1.538100e+04
 7.480000e+04 1.093220e+05 4.750000e+05 6.100000e+04 8.050000e+04
 6.575500e+04 2.600000e+03 1.550000e+04 5.070000e+04 4.400000e+05
 1.520000e+05 2.004000e+05 7.300000e+03 9.750000e+03 1.571380e+05
 2.850000e+05 1.279910e+05 1.312000e+04 8.750000e+04 6.220000e+04
 8.754000e+04 2.314380e+05 2.394510e+05 1.540000e+05 4.260000e+05
 1.820000e+05 2.150000e+05 7.730000e+04 6.126000e+04 1.760100e+04
 4.773000e+03 5.790000e+04 8.600000e+03 7.801000e+04 8.384400e+04
 2.399900e+04 9.140000e+04 1.785000e+05 6.695300e+04 1.660000e+05
 1.310000e+05 1.007500e+05 4.867600e+04 7.950000e+04 2.001850e+05
 4.902500e+04 7.646000e+04 4.737000e+04 4.521700e+04 2.223000e+05
 4.460000e+04 2.808000e+04 2.880000e+04 2.190000e+04 2.810000e+04
 7.673000e+03 9.627200e+04 2.250000e+04 7.400000e+03 3.700000e+05
 1.503600e+05 4.213000e+04 1.475000e+05 5.619400e+04 5.418800e+04
 5.404300e+04 6.665700e+04 3.558200e+04 5.432700e+04 7.949000e+03
 5.973400e+04 4.918500e+04 5.638900e+04 5.824500e+04 3.642200e+04
 4.253500e+04 4.073600e+04 5.624600e+04 5.540300e+04 1.053580e+05
 4.920000e+04 8.150000e+04 3.177000e+03 3.941400e+04 3.007800e+04
 4.458800e+04 4.990700e+04 6.708200e+04 1.128790e+05 1.020000e+04
 1.300000e+03 1.758020e+05 1.920000e+05 7.384000e+04 3.200000e+05
 2.485700e+04 2.644200e+04 5.080000e+04 4.014200e+04 9.400000e+03
 1.258400e+04 4.300000e+03 1.454800e+04 4.477200e+04 4.850000e+04
 2.878200e+04 2.845100e+04 3.650000e+04 4.488500e+04 1.311110e+05
 5.840000e+04 2.340000e+04 3.010000e+03 1.630000e+05 7.708800e+04
 1.365110e+05 3.671000e+04 2.818000e+04 4.407700e+04 5.576800e+04
 1.232780e+05 2.650000e+04 1.848400e+04 2.560000e+03 1.036550e+05
 5.697500e+04 1.870000e+05 2.180000e+05 7.325700e+04 2.632000e+04
 3.842600e+04 1.167000e+05 1.760620e+05 7.750000e+04 3.950000e+04
 5.589600e+04 3.040000e+04 1.640000e+05 2.710000e+05 7.526200e+04
 9.186300e+04 4.755200e+04 1.470000e+04 1.970000e+04 1.452410e+05
 9.550000e+04 5.347300e+04 7.595800e+04 3.159600e+04 8.571000e+04
 1.296270e+05 5.513000e+04 2.252200e+04 5.185600e+04 2.943400e+04
 3.450000e+04 6.825000e+03 1.120110e+05 5.353400e+04 2.481190e+05
 2.401900e+04 1.960000e+04 3.764120e+05 1.830000e+05 1.089160e+05
 5.986500e+04 6.814000e+04 5.319000e+04 7.010000e+04 4.772500e+04
 7.019500e+04 7.739500e+04 7.432100e+04 8.023500e+04 7.715000e+04
 6.110000e+04 8.230000e+04 8.205000e+04 2.989900e+04 5.923500e+04
 2.010000e+05 7.721500e+04 4.822800e+04 5.855900e+04 5.085600e+04
 1.830000e+04 5.929200e+04 2.114700e+04 6.117300e+04 9.156700e+04
 3.340000e+04 9.268600e+04 6.760000e+04 4.950000e+04 1.120480e+05
 3.064600e+04 4.301100e+04 1.043000e+05 7.350000e+04 2.800000e+05
 3.570000e+04 2.270000e+04 2.187100e+04 5.542500e+04 3.765900e+04
 3.750000e+04 1.980000e+04 4.562900e+04 6.885000e+04 4.577500e+04
 6.820300e+04 9.734300e+04 8.250700e+04 5.940000e+04 1.258760e+05
 5.680000e+04 6.520400e+04 2.286000e+03 1.573200e+04 4.952300e+04
 3.652100e+04 6.448100e+04 4.906000e+04 3.716100e+04 6.017500e+04
 4.995700e+04 4.323500e+04 5.069900e+04 1.000000e+00 5.007400e+04
 3.015400e+04 2.626300e+04 8.492500e+04 4.635700e+04 4.673700e+04
 1.100480e+05 1.863880e+05 2.017100e+04 3.715100e+04 5.816100e+04
 5.017100e+04 5.516100e+04 9.599000e+03 1.615100e+04 2.816100e+04

In [64]:
def get_brand_name(car_name):
    car_name = car_name.split(' ')[0]
    return car_name.strip()

In [65]:
def clean_data(value):
    if isinstance(value, (int, float)):
        return float(value)
    try:
        return float(str(value).split(' ')[0])
    except:
        return 0.0

cars_data['engine'] = cars_data['engine'].apply(clean_data)

In [66]:
def clean_data(value):
    value = value.split(' ')[0]
    value = value.strip()
    if value == '':
        value = 0
    return float(value)

In [67]:
get_brand_name('Maruti Swift Dzire VDI')

'Maruti'

In [68]:
cars_data['name'] = cars_data['name'].apply( get_brand_name)

In [69]:
cars_data['name'].unique()

<ArrowStringArray>
[       'Maruti',         'Skoda',         'Honda',       'Hyundai',
        'Toyota',          'Ford',       'Renault',      'Mahindra',
          'Tata',     'Chevrolet',        'Datsun',          'Jeep',
 'Mercedes-Benz',    'Mitsubishi',          'Audi',    'Volkswagen',
           'BMW',        'Nissan',         'Lexus',        'Jaguar',
          'Land',            'MG',         'Volvo',        'Daewoo',
           'Kia',          'Fiat',         'Force',    'Ambassador',
         'Ashok',         'Isuzu',          'Opel']
Length: 31, dtype: str

In [70]:
cars_data['mileage'] = cars_data['mileage'].apply(lambda x: float(str(x).split(' ')[0]) if str(x).split(' ')[0] != '' else 0.0)

In [71]:
cars_data['max_power'] = cars_data['max_power'].apply(lambda x: float(str(x).split(' ')[0]) if str(x).split(' ')[0] != '' else 0.0)

In [72]:
cars_data['engine'] = cars_data['engine'].apply(lambda x: float(str(x).split(' ')[0]) if str(x).split(' ')[0] != '' else 0.0)

In [73]:
for col in cars_data.columns:
    print('Unique values of ' + col)
    print(cars_data[col].unique())
    print("=====================\n")

Unique values of name
<ArrowStringArray>
[       'Maruti',         'Skoda',         'Honda',       'Hyundai',
        'Toyota',          'Ford',       'Renault',      'Mahindra',
          'Tata',     'Chevrolet',        'Datsun',          'Jeep',
 'Mercedes-Benz',    'Mitsubishi',          'Audi',    'Volkswagen',
           'BMW',        'Nissan',         'Lexus',        'Jaguar',
          'Land',            'MG',         'Volvo',        'Daewoo',
           'Kia',          'Fiat',         'Force',    'Ambassador',
         'Ashok',         'Isuzu',          'Opel']
Length: 31, dtype: str
=====================

Unique values of year
[2014. 2006. 2010. 2007. 2017. 2001. 2011. 2013. 2005. 2009. 2016. 2012.
 2002. 2015. 2018. 2019. 2008. 2020. 1999. 2000. 2003. 2004. 1994. 1998.
 1997. 1995. 1996.]
=====================

Unique values of selling_price
[  450000.   370000.   158000.   225000.   130000.   440000.    96000.
    45000.   350000.   200000.   500000.    92000.   280000.   180000.
   400000.   778000.   150000.   680000.   174000.   950000.   525000.
   600000.   575000.   275000.   300000.   220000.   254999.   670000.
   730000.   650000.   330000.   366000.  1149000.   425000.  2100000.
   925000.   675000.   819999.   390000.  1500000.   700000.  1450000.
  1090000.   850000.  1650000.  1750000.  1590000.  1689999.  1425000.
   265000.   190000.   630000.   540000.   448000.   745000.  1025000.
   235000.  1700000.  1200000.   610000.  2500000.   484999.   315000.
   290000.   455000.   351000.   175000.   565000.   120000.   725000.
   185000.   615000.   270000.   625000.   866000.   375000.   522000.
   451999.   475000.   780000.   595000.  1140000.   360000.   105000.
   135000.   690000.  3975000.  5150000.  3200000.  4100000.  4500000.
  6000000.  3790000.  5800000.  1864999.  2700000.   795000.  3400000.
  2650000.   535000.  5850000.   975000.   805000.  2625000.   811000.
   550000.   645000.  2550000.   599000.   875000.   894999.   340000.
  1525000.  2150000.  1900000.  2900000. 10000000.   160000.   515000.
    40000.   480000.   487000.   386000.   100000.   490000.   345000.
    85000.   215000.   320000.   459999.    65000.   720000.   800000.
   520000.   580000.   420000.  1250000.   830000.   335000.   329000.
   775000.   524000.   245000.   910000.   900000.   250000.  1100000.
   640000.   409999.   165000.    80000.  1000000.   110000.   170000.
  1380000.  1300000.   530000.   310000.  1150000.   380000.   404000.
   114999.   465000.   210000.  4600000.   509999.    90000.   409000.
   395000.    81000.   555000.   229999.  1210000.   325000.    60000.
    89000.   434999.  3000000.   570000.  1550000.    64000.   140000.
   503000.  3800000.  2000000.   740000.   750000.  5400000.  5500000.
   779000.  2475000.   240000.  1085000.    95000.  1290000.   219000.
   260000.   840000.   292000.   385000.  1050000.   735000.   560000.
   585000.   760000.   430000.   643000.   285000.   660000.   268000.
    88000.   561000.   755000.   125000.  1600000.   801000.   317000.
   495000.   236000.  1800000.   415000.   217000.   466000.   605000.
  1350000.   337000.   655000.   196000.   299000.   634000.  1225000.
   238000.   590000.   195000.   715000.   168000.   531000.  1625000.
   145000.   441000.    67500.   321000.   298000.  1075000.   681000.
   810000.   573000.   101000.  1019999.   244000.  1165000.   241000.
   327000.   620000.   204999.   576000.   695000.   231000.   261000.
   371000.   421000.   710000.  1040000.   199000.   305000.  1745000.
   611000.    75000.    55000.  1325000.   885000.   108000.   272000.
  1125000.   388000.   757000.   626000.   793000.  3750000.  1400000.
  1925000.   844999.  2940000.  1825000.   890000.   770000.   467000.
   711000.   511000.   166000.   392000.   833000.    35000.   880000.
  1030000.   521000.   451000.   472000.   649000.   429000.  1576000.
   825000.   470000.  1560000.  1950000.   786000.   731000.   191000.
   651000.   445000.    93150.   403000.   144000.    52000.   302000.
   869999.   155000.   246000.   405000.    70000.  3250000.  1143000.
   635000.  1575000.   318000.   152000.   248000.  1465000.  1080000.
   678000.  1460000.   756000.   665000.  2950000.   377000.  1675000.
   169000.   685000.   749000.   899000.   259000.   416000.   773000.
   889000.   118000.   256000.  1888000.    99000.  2280000.    31504.
   295000.   444000.   860000.  2450000.   198000.  2825000.  2125000.
  3350000.   365000.   919999.  2600000.   839000.  1594000.   161000.
   423000.   551000.    50000.   411000.  1530000.   376000.  1850000.
    86000.   822000.    30000.   252000.   131000.   128000.   790000.
   604000.  1175000.   141000.   151000.   577000.    83000.   946000.
   356000.   955000.   978999.   348000.   399000.   362000.   499000.
   358000.   278000.   426000.   211000.  1270000.   426999.   960000.
  1031000.    72000.   479000.   764000.  2199000.  3600000.   184000.
   119000.   267000.   328000.   112999.    39000.  2850000.  2800000.
  3900000.   221000.   631000.   308000.   940000.   361000.   355000.
  7200000.   930000.  1670000.   980000.   486000.   242000.   654000.
   835000.   408000.    94500.  1110000.   438999.   911999.   693000.
   449000.  1390000.   698000.   539000.   765000.   562000.   571000.
   589000.   227999.  1151000.  1295000.  4090000.   347000.   493000.
   545000.  1475000.   287000.  1630000.   501000.   181000.  2711000.
  1035000.   316000.   813000.  1190000.   378000.   156000.   194000.
   754000.    55599.  1511000.    78000.   250999.   312000.    66000.
   369000.   149000.   752000.   142000.   111000.   206000.   567000.
   699000.   632000.   905000.  1145000.    58000.   179000.  1515000.
   178000.   222000.   387000.  1405000.   282000.   458000.   157000.
   497000.  1227000.   574000.   121000.  3100000.    68000.  1920000.
   808000.   512000.   671000.   799000.  1365000.  1490000.    80500.
   189000.   892000.    93000.  1680000.   667000.   204000.    42000.
   694000.   861999.   476999.  5200000.  2375000.  2750000.  1385000.
   785000.  1275000.  1748999.   132000.    33351.  2064000.   469000.
   906000.   797000.  6223000.  5923000.  6523000.   122000.   891000.
   346000.   532000.   974000.   483000.   138000.   432000.  1757000.
   412000.   126000.   736000.   579000.   187000.  4000000.  1898999.
   482000.   401000.   737000.   291000.   999000.   957000.   834000.
   297000.   669000.   616000.   129000.   115999.   861000.  3251000.
   911000.   148000.   433000.   488000.    67000.   516000.   136000.
    29999.   124000.  1938000.   172000.    59000.  3500000.   537000.
   849000.   851000.   597000.   741000.   556000.   549000.   679000.
   969999.  1237000.    31000.   666000.    54000.   374000.   455999.
   453000.   258000.   428000.   262000.   389000.   339000.   277000.
   578000.   684000.   949000.   227000.  5830000.   721000.   751000.
  2400000.   990000.  1282000.  1147000.   558000.   722000.   563000.
  2300000.  2200000.   488999.   276000.   434000.   372000.  1520000.
   202999.   541000.   254000.   528000.   102000.   311000.   977000.
  1251000.  1445000.    98000.    59259.   153000.  1051000.   591000.
   319000.   454000.  1160000.  3300000.   791000.   802999.  1789999.
  1044999.   279000.   944999.  1859000.  2175000.   430999.   803999.
   934000.   357000.   965000.   341000.    75527.  1132000.   352000.
   252999.   313000.   391000.  2051000.   212000.  2575000.  1516000.
   359000.   209000.  1220000.  1180000.    45957.  1265000.   382000.
   526000.    90177.    46000.   307000.   746000.]
=====================

Unique values of km_driven
[1.455000e+05 1.200000e+05 1.400000e+05 1.270000e+05 4.500000e+04
 1.750000e+05 5.000000e+03 9.000000e+04 1.690000e+05 6.800000e+04
 1.000000e+05 4.000000e+04 7.000000e+04 5.300000e+04 8.000000e+04
 5.000000e+04 7.200000e+04 3.500000e+04 2.800000e+04 2.500000e+04
 2.388000e+03 1.620000e+04 1.000000e+04 1.500000e+04 4.200000e+04
 6.000000e+04 7.600000e+04 2.890000e+04 8.630000e+04 2.330000e+04
 3.260000e+04 1.030000e+04 7.700000e+04 9.900000e+04 2.780000e+04
 4.980000e+04 1.510000e+05 5.470000e+04 6.400000e+04 6.300000e+04
 1.277000e+05 3.390000e+04 5.900000e+04 1.100000e+05 1.470000e+05
 3.000000e+04 1.350000e+05 9.850000e+03 7.800000e+04 1.700000e+05
 4.900000e+04 3.200000e+04 3.800000e+04 4.400000e+04 5.550000e+04
 6.150000e+04 1.500000e+05 3.780000e+04 1.140000e+05 4.800000e+04
 6.900000e+04 1.300000e+04 7.613900e+04 6.500000e+04 1.303000e+03
 3.180000e+04 2.000000e+04 1.700000e+04 2.100000e+04 3.700000e+04
 2.950000e+04 7.500000e+03 1.900000e+04 4.100000e+04 3.900000e+04
 2.200000e+04 4.700000e+04 7.220000e+04 4.990000e+04 9.000000e+03
 1.100000e+04 9.500000e+04 1.800000e+04 4.610000e+04 1.600000e+04
 9.654000e+03 2.430000e+04 4.216300e+04 8.000000e+03 1.200000e+04
 7.100000e+04 9.500000e+03 3.660000e+04 1.400000e+04 1.206000e+05
 8.600000e+04 7.800000e+03 3.137700e+04 7.500000e+04 9.300000e+04
 1.250000e+05 1.350000e+04 1.625000e+05 9.250000e+04 1.580000e+05
 2.000000e+03 1.810000e+05 1.930000e+05 1.223580e+05 9.520000e+04
 3.303300e+04 6.306300e+04 2.078900e+05 7.976000e+03 1.650000e+04
 9.936100e+04 3.300000e+04 8.010000e+04 1.600000e+05 2.600000e+04
 2.900000e+04 5.800000e+04 3.600000e+04 1.850000e+05 1.620000e+05
 6.700000e+04 5.200000e+04 6.808900e+04 5.834300e+04 3.881700e+04
 5.649400e+04 7.932800e+04 5.621000e+03 2.553800e+04 6.977900e+04
 5.629000e+04 8.500000e+03 7.032000e+03 1.060000e+05 2.400000e+05
 2.140000e+05 1.000000e+03 2.650000e+05 1.340000e+05 2.136000e+03
 2.500000e+05 1.300000e+05 9.950000e+04 1.190000e+05 4.466500e+04
 1.230000e+05 3.400000e+04 1.460000e+05 8.500000e+04 2.018500e+05
 4.600000e+04 1.900000e+05 4.300000e+04 1.420000e+04 1.910000e+04
 5.400000e+04 1.015000e+05 5.573500e+04 1.500000e+03 1.814910e+05
 5.331900e+04 4.090600e+04 3.171100e+04 4.375500e+04 6.669300e+04
 5.954900e+04 9.438500e+04 7.373000e+04 2.218890e+05 1.161040e+05
 1.505460e+05 1.481200e+05 1.420000e+05 1.260000e+05 2.400000e+04
 1.010000e+05 1.680000e+05 1.650000e+05 9.850000e+04 9.800000e+04
 7.780000e+04 5.149200e+04 1.360000e+05 9.100000e+04 1.670000e+05
 1.800000e+05 6.000000e+03 9.150000e+04 1.324780e+05 5.100000e+04
 1.050000e+05 1.375000e+05 8.800000e+04 1.560600e+05 1.070000e+05
 5.700000e+04 3.000000e+05 2.000000e+05 1.894500e+04 1.440000e+05
 1.078250e+05 1.620000e+03 1.410000e+05 1.080000e+05 5.500000e+04
 3.794400e+04 9.040000e+04 9.600000e+04 1.936230e+05 6.318600e+04
 2.190000e+05 2.300000e+04 9.400000e+04 1.405000e+05 1.430000e+05
 1.950000e+05 3.600030e+05 8.079000e+03 1.143680e+05 7.999000e+04
 8.163200e+04 1.552010e+05 1.015040e+05 9.016500e+04 8.601700e+04
 8.503600e+04 1.255310e+05 2.060000e+05 4.970000e+04 7.400000e+04
 6.550000e+03 5.600000e+04 4.177900e+04 3.100000e+04 1.353400e+04
 7.000000e+03 2.815600e+04 6.330900e+04 1.550000e+05 1.150000e+04
 3.000000e+03 1.570000e+05 2.700000e+04 2.630000e+04 8.910000e+04
 1.040000e+05 2.100000e+05 2.160000e+05 8.400000e+04 1.610000e+05
 7.211300e+04 1.130000e+05 9.644300e+04 5.150000e+04 1.045000e+05
 4.910200e+04 8.100000e+04 2.270000e+05 1.170000e+05 8.576000e+03
 1.972300e+04 2.144600e+04 5.228900e+04 5.223600e+04 5.447000e+04
 2.547100e+04 3.392800e+04 5.973600e+04 5.429000e+04 2.118000e+03
 6.137900e+04 5.854400e+04 7.438100e+04 6.398200e+04 5.642900e+04
 1.950000e+04 5.683200e+04 3.052800e+04 6.528500e+04 2.010200e+04
 5.238000e+04 7.425000e+04 5.724700e+04 1.780000e+05 4.232300e+04
 4.246200e+04 5.472300e+04 4.254500e+04 2.037500e+04 4.397800e+04
 4.020000e+04 2.723300e+04 2.883200e+04 1.030000e+05 1.425000e+05
 1.150000e+05 3.550000e+04 1.750000e+04 9.200000e+04 4.500000e+03
 8.300000e+04 6.750000e+03 1.850000e+04 5.047800e+04 9.200000e+03
 2.300000e+03 4.295000e+03 5.229000e+03 4.701000e+03 6.757000e+03
 2.818200e+04 1.153300e+04 1.168800e+04 5.772800e+04 2.371200e+04
 7.067000e+04 4.338100e+04 7.901100e+04 5.850000e+04 4.350000e+04
 1.270000e+04 4.945500e+04 4.681500e+04 3.340000e+05 1.008750e+05
 1.180000e+05 1.280000e+05 1.440300e+05 1.760000e+05 8.900000e+04
 9.700000e+04 1.280000e+04 6.510000e+04 1.520000e+04 8.200000e+04
 1.165000e+05 1.450000e+05 7.300000e+04 1.132260e+05 1.605000e+05
 1.320000e+05 2.170000e+05 1.390000e+05 3.500000e+03 6.200000e+04
 1.500000e+06 1.200050e+05 1.683000e+04 9.346800e+04 1.658900e+04
 5.320100e+04 2.527200e+04 5.361900e+04 6.001000e+03 2.020000e+05
 7.171700e+04 8.432100e+04 1.770000e+05 2.050000e+05 4.180000e+04
 8.870000e+04 1.880000e+05 2.250000e+05 5.500000e+03 4.875000e+03
 2.700000e+03 5.851100e+04 2.623500e+04 2.676600e+04 1.600000e+03
 2.452200e+04 1.366300e+04 5.894500e+04 3.750000e+05 1.569750e+05
 2.762000e+04 1.432000e+05 1.380000e+05 1.890000e+05 1.560000e+05
 1.080000e+04 6.750000e+04 2.550000e+05 7.185000e+04 1.120000e+05
 1.590000e+05 7.613100e+04 5.177700e+04 6.478800e+04 4.695100e+04
 7.453700e+04 2.350000e+04 6.860000e+04 1.388700e+04 6.600000e+04
 2.440000e+04 2.750000e+04 6.784000e+04 3.800000e+05 1.128800e+05
 6.191500e+04 1.840000e+05 6.200000e+03 1.670000e+04 7.967000e+03
 9.656000e+03 6.860900e+04 3.336000e+04 1.431700e+04 8.723700e+04
 6.296000e+04 2.663400e+04 1.637200e+05 6.799800e+04 2.070600e+04
 1.005810e+05 6.730300e+04 7.913900e+04 8.478400e+04 1.303760e+05
 3.350000e+04 2.205300e+04 7.843200e+04 2.700000e+05 7.200000e+03
 1.175000e+05 7.850000e+04 1.157170e+05 4.000000e+03 2.643200e+04
 4.670200e+04 4.670600e+04 5.352300e+04 5.636500e+04 4.956300e+04
 5.643200e+04 5.236500e+04 5.351200e+04 4.653300e+04 5.863200e+04
 6.530000e+04 3.939500e+04 2.300000e+05 3.250000e+04 6.480000e+04
 2.480000e+05 6.644400e+04 2.184630e+05 1.530000e+05 8.718500e+04
 1.370000e+05 3.564000e+03 4.875600e+04 8.032200e+04 1.730000e+05
 1.480000e+05 6.500000e+03 2.200000e+05 1.089570e+05 2.220000e+04
 2.600000e+05 4.210800e+04 7.900000e+04 1.710000e+04 4.300100e+04
 1.006000e+05 9.238500e+04 1.160000e+05 7.250000e+04 8.250000e+04
 5.060000e+04 1.210000e+05 1.019030e+05 8.556800e+04 3.100000e+03
 1.860000e+05 5.930000e+04 8.932200e+04 4.830000e+04 2.351100e+04
 2.251200e+04 6.290000e+04 5.244200e+04 3.415600e+04 3.415200e+04
 6.284100e+04 3.860000e+04 2.765400e+04 4.869800e+04 3.299500e+04
 9.015000e+04 8.570000e+04 2.533900e+04 4.123200e+04 6.824000e+04
 9.265100e+04 8.875400e+04 2.370000e+04 6.950000e+04 2.805000e+04
 2.294700e+04 7.672000e+03 3.665900e+04 4.450000e+04 9.900000e+03
 1.243160e+05 6.544000e+03 4.960000e+04 1.980000e+05 1.039940e+05
 3.500800e+04 3.110000e+04 4.231200e+04 5.489100e+04 1.889000e+04
 7.501000e+04 4.337000e+03 1.449500e+04 8.358500e+04 4.840600e+04
 5.623900e+04 3.324300e+04 1.585800e+04 8.784700e+04 8.700000e+04
 1.120720e+05 5.226900e+04 1.578000e+04 2.360457e+06 1.088000e+05
 1.250000e+04 5.774140e+05 1.219410e+05 1.521860e+05 8.224600e+04
 8.958000e+04 2.789000e+03 3.527800e+04 2.860000e+03 7.856200e+04
 3.608800e+04 1.290000e+05 5.000000e+05 1.330000e+05 6.450000e+04
 2.450000e+04 4.550000e+04 7.150000e+04 9.350000e+04 6.030000e+04
 4.439100e+04 5.631500e+04 1.515100e+04 1.143210e+05 3.733300e+04
 3.300000e+05 2.910000e+05 2.150000e+04 1.970000e+05 4.030000e+04
 3.003000e+04 2.902900e+04 7.207200e+04 8.208200e+04 8.060000e+04
 5.860900e+04 3.300300e+04 1.655000e+05 5.800000e+03 6.870000e+04
 1.029960e+05 9.650000e+04 5.241200e+04 8.547200e+04 8.745200e+04
 6.653000e+04 3.233100e+04 1.720000e+05 2.345600e+04 1.365000e+05
 1.110000e+05 4.250000e+04 4.720000e+04 2.460000e+05 5.200000e+03
 1.050000e+04 9.333100e+04 1.090000e+05 5.400000e+03 1.020000e+05
 2.970000e+04 7.600000e+03 2.934000e+04 8.080000e+04 2.426500e+04
 5.690000e+04 8.820000e+04 4.080000e+04 8.588000e+03 3.050000e+05
 2.120000e+05 1.012000e+05 1.791500e+05 8.448700e+04 2.640000e+05
 5.114600e+04 2.980000e+05 1.490000e+05 2.919770e+05 3.680000e+04
 5.220000e+04 2.482000e+05 7.720000e+03 5.788200e+04 2.420000e+05
 5.538000e+04 1.881600e+04 3.301900e+04 4.774700e+04 4.590000e+04
 6.869700e+04 1.472790e+05 2.470000e+04 4.352600e+04 5.588500e+04
 1.603400e+04 1.560400e+05 9.341500e+04 1.220000e+05 6.851900e+04
 2.296600e+04 2.350000e+03 5.987200e+04 9.118200e+04 5.950000e+04
 7.550000e+04 1.525000e+05 6.912300e+04 7.752400e+04 4.052300e+04
 2.360000e+04 2.900000e+05 2.417700e+04 1.217790e+05 1.538100e+04
 7.480000e+04 1.093220e+05 4.750000e+05 6.100000e+04 8.050000e+04
 6.575500e+04 2.600000e+03 1.550000e+04 5.070000e+04 4.400000e+05
 1.520000e+05 2.004000e+05 7.300000e+03 9.750000e+03 1.571380e+05
 2.850000e+05 1.279910e+05 1.312000e+04 8.750000e+04 6.220000e+04
 8.754000e+04 2.314380e+05 2.394510e+05 1.540000e+05 4.260000e+05
 1.820000e+05 2.150000e+05 7.730000e+04 6.126000e+04 1.760100e+04
 4.773000e+03 5.790000e+04 8.600000e+03 7.801000e+04 8.384400e+04
 2.399900e+04 9.140000e+04 1.785000e+05 6.695300e+04 1.660000e+05
 1.310000e+05 1.007500e+05 4.867600e+04 7.950000e+04 2.001850e+05
 4.902500e+04 7.646000e+04 4.737000e+04 4.521700e+04 2.223000e+05
 4.460000e+04 2.808000e+04 2.880000e+04 2.190000e+04 2.810000e+04
 7.673000e+03 9.627200e+04 2.250000e+04 7.400000e+03 3.700000e+05
 1.503600e+05 4.213000e+04 1.475000e+05 5.619400e+04 5.418800e+04
 5.404300e+04 6.665700e+04 3.558200e+04 5.432700e+04 7.949000e+03
 5.973400e+04 4.918500e+04 5.638900e+04 5.824500e+04 3.642200e+04
 4.253500e+04 4.073600e+04 5.624600e+04 5.540300e+04 1.053580e+05
 4.920000e+04 8.150000e+04 3.177000e+03 3.941400e+04 3.007800e+04
 4.458800e+04 4.990700e+04 6.708200e+04 1.128790e+05 1.020000e+04
 1.300000e+03 1.758020e+05 1.920000e+05 7.384000e+04 3.200000e+05
 2.485700e+04 2.644200e+04 5.080000e+04 4.014200e+04 9.400000e+03
 1.258400e+04 4.300000e+03 1.454800e+04 4.477200e+04 4.850000e+04
 2.878200e+04 2.845100e+04 3.650000e+04 4.488500e+04 1.311110e+05
 5.840000e+04 2.340000e+04 3.010000e+03 1.630000e+05 7.708800e+04
 1.365110e+05 3.671000e+04 2.818000e+04 4.407700e+04 5.576800e+04
 1.232780e+05 2.650000e+04 1.848400e+04 2.560000e+03 1.036550e+05
 5.697500e+04 1.870000e+05 2.180000e+05 7.325700e+04 2.632000e+04
 3.842600e+04 1.167000e+05 1.760620e+05 7.750000e+04 3.950000e+04
 5.589600e+04 3.040000e+04 1.640000e+05 2.710000e+05 7.526200e+04
 9.186300e+04 4.755200e+04 1.470000e+04 1.970000e+04 1.452410e+05
 9.550000e+04 5.347300e+04 7.595800e+04 3.159600e+04 8.571000e+04
 1.296270e+05 5.513000e+04 2.252200e+04 5.185600e+04 2.943400e+04
 3.450000e+04 6.825000e+03 1.120110e+05 5.353400e+04 2.481190e+05
 2.401900e+04 1.960000e+04 3.764120e+05 1.830000e+05 1.089160e+05
 5.986500e+04 6.814000e+04 5.319000e+04 7.010000e+04 4.772500e+04
 7.019500e+04 7.739500e+04 7.432100e+04 8.023500e+04 7.715000e+04
 6.110000e+04 8.230000e+04 8.205000e+04 2.989900e+04 5.923500e+04
 2.010000e+05 7.721500e+04 4.822800e+04 5.855900e+04 5.085600e+04
 1.830000e+04 5.929200e+04 2.114700e+04 6.117300e+04 9.156700e+04
 3.340000e+04 9.268600e+04 6.760000e+04 4.950000e+04 1.120480e+05
 3.064600e+04 4.301100e+04 1.043000e+05 7.350000e+04 2.800000e+05
 3.570000e+04 2.270000e+04 2.187100e+04 5.542500e+04 3.765900e+04
 3.750000e+04 1.980000e+04 4.562900e+04 6.885000e+04 4.577500e+04
 6.820300e+04 9.734300e+04 8.250700e+04 5.940000e+04 1.258760e+05
 5.680000e+04 6.520400e+04 2.286000e+03 1.573200e+04 4.952300e+04
 3.652100e+04 6.448100e+04 4.906000e+04 3.716100e+04 6.017500e+04
 4.995700e+04 4.323500e+04 5.069900e+04 1.000000e+00 5.007400e+04
 3.015400e+04 2.626300e+04 8.492500e+04 4.635700e+04 4.673700e+04
 1.100480e+05 1.863880e+05 2.017100e+04 3.715100e+04 5.816100e+04
 5.017100e+04 5.516100e+04 9.599000e+03 1.615100e+04 2.816100e+04
 8.086800e+04 1.940000e+05 1.910000e+05]
=====================

Unique values of fuel
<ArrowStringArray>
['Diesel', 'Petrol', 'LPG', 'CNG']
Length: 4, dtype: str
=====================

Unique values of seller_type
<ArrowStringArray>
['Individual', 'Dealer', 'Trustmark Dealer']
Length: 3, dtype: str
=====================

Unique values of transmission
<ArrowStringArray>
['Manual', 'Automatic']
Length: 2, dtype: str
=====================

Unique values of owner

In [74]:
cars_data.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
mileage          0
engine           0
max_power        0
seats            0
dtype: int64

In [75]:
cars_data['name'] = cars_data['name'].replace(
    ['Maruti','Skoda','Honda','Hyundai','Toyota','Ford','Renault',
     'Mahindra','Tata','Chevrolet','Datsun','Jeep','Mercedes-Benz',
     'Mitsubishi','Audi','Volkswagen','BMW','Nissan','Lexus',
     'Jaguar','Land','MG','Volvo','Daewoo','Kia','Fiat','Force',
     'Ambassador','Ashok','Isuzu','Opel'],
    [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
)

In [76]:
cars_data['transmission'].unique()

<ArrowStringArray>
['Manual', 'Automatic']
Length: 2, dtype: str

In [77]:
cars_data['transmission'] = cars_data['transmission'].replace(
    ['Manual', 'Automatic'],
    [1, 2]
)

In [78]:
cars_data['seller_type'].unique()

<ArrowStringArray>
['Individual', 'Dealer', 'Trustmark Dealer']
Length: 3, dtype: str

In [79]:
cars_data['seller_type'] = cars_data['seller_type'].replace(
    ['Individual', 'Dealer', 'Trustmark Dealer'],
    [1, 2, 3]
)

In [80]:
cars_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6717 entries, 0 to 6716
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6717 non-null   object
 1   year           6717 non-null   float64
 2   selling_price  6717 non-null   float64
 3   km_driven      6717 non-null   float64
 4   fuel           6717 non-null   str
 5   seller_type    6717 non-null   object
 6   transmission   6717 non-null   object
 7   owner          6717 non-null   str
 8   mileage        6717 non-null   float64
 9   engine         6717 non-null   float64
 10  max_power      6717 non-null   float64
 11  seats          6717 non-null   float64
dtypes: float64(7), object(3), str(2)
memory usage: 746.0+ KB

In [81]:
cars_data['fuel'].unique()

<ArrowStringArray>
['Diesel', 'Petrol', 'LPG', 'CNG']
Length: 4, dtype: str

In [82]:
cars_data['fuel'] = cars_data['fuel'].replace({
    'Diesel': 1,
    'Petrol': 2,
    'LPG': 3,
    'CNG': 4
})

In [83]:
cars_data.reset_index(inplace=True)

In [85]:
cars_data

,index,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,0,1,2014.0,450000.0,145500.0,1,1,1,First Owner,23.40,1248.0,74.00,5.0
1,1,2,2014.0,370000.0,120000.0,1,1,1,Second Owner,21.14,1498.0,103.52,5.0
2,2,3,2006.0,158000.0,140000.0,2,1,1,Third Owner,17.70,1497.0,78.00,5.0
3,3,4,2010.0,225000.0,127000.0,1,1,1,First Owner,23.00,1396.0,90.00,5.0
4,4,1,2007.0,130000.0,120000.0,2,1,1,First Owner,16.10,1298.0,88.20,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6712,6712,1,2013.0,260000.0,50000.0,2,1,1,Second Owner,18.90,998.0,67.10,5.0
6713,6713,4,2014.0,475000.0,80000.0,1,1,1,Second Owner,22.54,1396.0,88.73,5.0
6714,6714,4,2013.0,320000.0,110000.0,2,1,1,First Owner,18.50,1197.0,82.85,5.0
6715,6715,4,2007.0,135000.0,119000.0,1,1,1,Fourth & Above Owner,16.80,1493.0,110.00,5.0
6716,6716,1,2009.0,382000.0,120000.0,1,1,1,First Owner,19.30,1248.0,73.90,5.0

In [46]:
cars_data['owner'].unique()

array([1, 2, 3, 4, 5], dtype=object)

In [86]:
cars_data['owner'] = cars_data['owner'].replace({
    'First Owner': 1,
    'Second Owner': 2,
    'Third Owner': 3,
    'Fourth & Above Owner': 4,
    'Test Drive Car': 5
})

In [87]:
input_data = cars_data.drop(columns=['selling_price'])
output_data = cars_data['selling_price']

In [88]:
x_train,x_test,y_train,y_test=train_test_split(input_data,output_data,test_size=0.2)

In [89]:
model=LinearRegression()

In [90]:
model.fit(x_train,y_train)

LinearRegression()

In [91]:
predict=model.predict(x_test)

In [92]:
predict

array([ 833487.80898249, 1035671.6006415 ,  500891.65297899, ...,
        121305.42222823,  665406.01695865,  209324.90040675],
      shape=(1344,))

In [93]:
x_train.head(1)

,index,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
1879,1879,3,2005.0,80000.0,2,1,2,2,9.0,2997.0,218.0,5.0

In [117]:
input_data_model = pd.DataFrame(
    [[5,2015,120000,1,1,1,1,12.99,2494.0,100.6,8.0]],
    columns=['name','year','km_driven','fuel','seller_type','transmission','owner','mileage','engine','max_power','seats'])

In [118]:
model.predict(input_data_model)

ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- index

In [ ]:
import pickle as pk

In [ ]:
pk.dump(model,open('model.pk1','wb'))